"""Extension sessions and installations (A5).

An extension token is not a dashboard token. It lives in browser storage, which is a weaker
place than a dashboard tab, so it is issued separately, expires sooner, is scoped to the
extension endpoints, and can be revoked by deleting a row rather than by waiting for an expiry.
"""
from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime

import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.core.errors import AuthenticationError, ValidationError
from app.core.security import TOKEN_USE_EXTENSION, create_access_token
from app.models.entities import WorkspaceMember
from app.models.extension import ExtensionInstallation
from app.services.audit import AuditLogService

#: An instance id is generated by the extension and means nothing outside this product. It is
#: constrained so it cannot smuggle a URL, a token or anything else through the field.
INSTANCE_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{8,64}$")
VERSION_PATTERN = re.compile(r"^\d{1,3}(\.\d{1,3}){0,3}$")


def _version_tuple(value: str) -> tuple[int, ...]:
    return tuple(int(part) for part in value.split(".") if part.isdigit())


class ExtensionInstallationService:
    def __init__(self, session: Session, workspace_id: uuid.UUID, audit: AuditLogService) -> None:
        self.session = session
        self.workspace_id = workspace_id
        self.audit = audit

    def get_active(self, installation_id: uuid.UUID) -> ExtensionInstallation | None:
        return self.session.execute(
            sa.select(ExtensionInstallation).where(
                ExtensionInstallation.id == installation_id,
                ExtensionInstallation.workspace_id == self.workspace_id,
                ExtensionInstallation.revoked_at.is_(None),
            )
        ).scalars().first()

    def list_for_user(self, user_id: uuid.UUID) -> list[ExtensionInstallation]:
        return list(
            self.session.execute(
                sa.select(ExtensionInstallation)
                .where(
                    ExtensionInstallation.workspace_id == self.workspace_id,
                    ExtensionInstallation.user_id == user_id,
                )
                .order_by(ExtensionInstallation.created_at.desc())
            ).scalars().all()
        )

    def register(
        self,
        *,
        user_id: uuid.UUID,
        extension_instance_id: str,
        extension_version: str,
        label: str,
    ) -> ExtensionInstallation:
        """Reuse the live installation for this browser profile, or create one.

        Reusing it means re-exchanging a session does not accumulate a row per sign-in, and the
        operator's installation list stays a list of browsers rather than a list of logins.
        """
        existing = self.session.execute(
            sa.select(ExtensionInstallation).where(
                ExtensionInstallation.workspace_id == self.workspace_id,
                ExtensionInstallation.user_id == user_id,
                ExtensionInstallation.extension_instance_id == extension_instance_id,
                ExtensionInstallation.revoked_at.is_(None),
            )
        ).scalars().first()

        now = datetime.now(UTC)
        if existing is not None:
            existing.extension_version = extension_version
            existing.last_seen_at = now
            if label:
                existing.label = label
            self.session.flush()
            self.audit.record(
                action="extension_installation.reconnected",
                entity_type="extension_installation",
                entity_id=existing.id,
                after={"extension_version": extension_version, "label": existing.label},
            )
            return existing

        installation = ExtensionInstallation(
            workspace_id=self.workspace_id,
            user_id=user_id,
            extension_instance_id=extension_instance_id,
            extension_version=extension_version,
            label=label,
            last_seen_at=now,
        )
        self.session.add(installation)
        self.session.flush()
        self.audit.record(
            action="extension_installation.created",
            entity_type="extension_installation",
            entity_id=installation.id,
            after={"extension_version": extension_version, "label": label},
        )
        return installation

    def touch(self, installation: ExtensionInstallation, *, version: str | None = None) -> None:
        """Record liveness without writing an audit row per page view."""
        installation.last_seen_at = datetime.now(UTC)
        if version and version != installation.extension_version:
            installation.extension_version = version
        self.session.flush()

    def revoke(self, installation: ExtensionInstallation, *, reason: str) -> ExtensionInstallation:
        if installation.revoked_at is not None:
            return installation
        installation.revoked_at = datetime.now(UTC)
        installation.revoked_reason = reason[:200]
        self.session.flush()
        self.audit.record(
            action="extension_installation.revoked",
            entity_type="extension_installation",
            entity_id=installation.id,
            after={"revoked_reason": installation.revoked_reason},
        )
        return installation


class ExtensionSessionService:
    """Exchanges a dashboard session for a scope-limited extension session."""

    def __init__(self, session: Session, workspace_id: uuid.UUID, audit: AuditLogService) -> None:
        self.session = session
        self.workspace_id = workspace_id
        self.audit = audit
        self.installations = ExtensionInstallationService(session, workspace_id, audit)

    @staticmethod
    def validate_client(*, extension_instance_id: str, extension_version: str) -> None:
        if not INSTANCE_ID_PATTERN.match(extension_instance_id or ""):
            raise ValidationError(
                "The extension instance id must be 8–64 characters of letters, digits, "
                "hyphen or underscore."
            )
        if not VERSION_PATTERN.match(extension_version or ""):
            raise ValidationError("The extension version must look like 1.2.3.")
        minimum = get_settings().extension_minimum_version.strip()
        if minimum and _version_tuple(extension_version) < _version_tuple(minimum):
            raise ValidationError(
                f"This extension build is older than the minimum supported version {minimum}. "
                "Update the extension and sign in again."
            )

    def exchange(
        self,
        *,
        user_id: uuid.UUID,
        membership: WorkspaceMember,
        extension_instance_id: str,
        extension_version: str,
        label: str,
    ) -> tuple[str, datetime, ExtensionInstallation]:
        self.validate_client(
            extension_instance_id=extension_instance_id, extension_version=extension_version
        )
        installation = self.installations.register(
            user_id=user_id,
            extension_instance_id=extension_instance_id,
            extension_version=extension_version,
            label=label,
        )
        settings = get_settings()
        token, expires_at = create_access_token(
            subject=str(user_id),
            workspace_id=str(self.workspace_id),
            role=membership.role.value,
            token_use=TOKEN_USE_EXTENSION,
            expires_in_minutes=settings.extension_token_expire_minutes,
            extra_claims={"installation_id": str(installation.id)},
        )
        self.audit.record(
            action="extension_session.issued",
            entity_type="extension_installation",
            entity_id=installation.id,
            # The token itself is never recorded — only that one was issued, and until when.
            after={"expires_at": expires_at.isoformat(), "extension_version": extension_version},
        )
        return token, expires_at, installation

    def load_installation(self, installation_id: str | None) -> ExtensionInstallation:
        if not installation_id:
            raise AuthenticationError("This extension session is not valid. Connect again.")
        try:
            parsed = uuid.UUID(installation_id)
        except (ValueError, TypeError) as exc:
            raise AuthenticationError("This extension session is not valid. Connect again.") from exc
        installation = self.installations.get_active(parsed)
        if installation is None:
            raise AuthenticationError(
                "This extension session has been revoked. Connect the extension again."
            )
        return installation
