"""A1 account registry and stability readiness

Revision ID: 948a035ab4a4
Revises: 
Create Date: 2026-09-04 20:35:21.288835
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_a1_registry'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_logs_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index('ix_audit_logs_workspace_id_created_at', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('browser_profile_references',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('profile_reference', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('local_or_remote', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_browser_profile_references_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_profile_references')),
    sa.UniqueConstraint('workspace_id', 'provider', 'profile_reference', name=op.f('uq_browser_profile_references_workspace_id_provider_profile_reference'))
    )
    op.create_index(op.f('ix_browser_profile_references_workspace_id'), 'browser_profile_references', ['workspace_id'], unique=False)
    op.create_index('ix_browser_profile_references_workspace_id_archived_at', 'browser_profile_references', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('business_managers',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_business_managers_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_managers')),
    sa.UniqueConstraint('workspace_id', 'external_id', name=op.f('uq_business_managers_workspace_id_external_id'))
    )
    op.create_index(op.f('ix_business_managers_workspace_id'), 'business_managers', ['workspace_id'], unique=False)
    op.create_index('ix_business_managers_workspace_id_archived_at', 'business_managers', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('pages',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_page_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pages_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('workspace_id', 'external_page_id', name=op.f('uq_pages_workspace_id_external_page_id'))
    )
    op.create_index(op.f('ix_pages_workspace_id'), 'pages', ['workspace_id'], unique=False)
    op.create_index('ix_pages_workspace_id_archived_at', 'pages', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('payment_profile_references',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('reference_code', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('billing_country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_payment_profile_references_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_profile_references')),
    sa.UniqueConstraint('workspace_id', 'reference_code', name=op.f('uq_payment_profile_references_workspace_id_reference_code'))
    )
    op.create_index(op.f('ix_payment_profile_references_workspace_id'), 'payment_profile_references', ['workspace_id'], unique=False)
    op.create_index('ix_payment_profile_references_workspace_id_archived_at', 'payment_profile_references', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('personal_account_references',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_reference_id', sa.String(length=120), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_personal_account_references_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_account_references')),
    sa.UniqueConstraint('workspace_id', 'external_reference_id', name=op.f('uq_personal_account_references_workspace_id_external_reference_id'))
    )
    op.create_index(op.f('ix_personal_account_references_workspace_id'), 'personal_account_references', ['workspace_id'], unique=False)
    op.create_index('ix_personal_account_references_workspace_id_archived_at', 'personal_account_references', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('pixels',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_pixel_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pixels_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pixels')),
    sa.UniqueConstraint('workspace_id', 'external_pixel_id', name=op.f('uq_pixels_workspace_id_external_pixel_id'))
    )
    op.create_index(op.f('ix_pixels_workspace_id'), 'pixels', ['workspace_id'], unique=False)
    op.create_index('ix_pixels_workspace_id_archived_at', 'pixels', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('proxy_references',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('proxy_reference', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTRICTED', name='reference_status', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_proxy_references_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxy_references')),
    sa.UniqueConstraint('workspace_id', 'provider', 'proxy_reference', name=op.f('uq_proxy_references_workspace_id_provider_proxy_reference'))
    )
    op.create_index(op.f('ix_proxy_references_workspace_id'), 'proxy_references', ['workspace_id'], unique=False)
    op.create_index('ix_proxy_references_workspace_id_archived_at', 'proxy_references', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'BUYER', 'VIEWER', 'AUDITOR', name='workspace_role', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_members_workspace_id_user_id'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('ad_accounts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_account_id', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.Enum('BUSINESS_MANAGER', 'PERSONAL_REFERENCE', 'UNKNOWN', name='account_type', native_enum=False, length=48), nullable=False),
    sa.Column('business_manager_id', sa.Uuid(), nullable=True),
    sa.Column('personal_account_reference_id', sa.Uuid(), nullable=True),
    sa.Column('owner_label', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'WARNING', 'RESTRICTED', 'DISABLED', 'ARCHIVED', name='account_status', native_enum=False, length=48), nullable=False),
    sa.Column('readiness_status', sa.Enum('UNKNOWN', 'NOT_READY', 'READY_WITH_WARNINGS', 'OPERATIONALLY_READY', name='readiness_status', native_enum=False, length=48), nullable=False),
    sa.Column('readiness_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_manual_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_page', sa.Boolean(), nullable=False),
    sa.Column('requires_pixel', sa.Boolean(), nullable=False),
    sa.Column('landing_page_url', sa.String(length=2048), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_manager_id'], ['business_managers.id'], name=op.f('fk_ad_accounts_business_manager_id_business_managers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['personal_account_reference_id'], ['personal_account_references.id'], name=op.f('fk_ad_accounts_personal_account_reference_id_personal_account_references'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ad_accounts_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_accounts')),
    sa.UniqueConstraint('workspace_id', 'external_account_id', name=op.f('uq_ad_accounts_workspace_id_external_account_id'))
    )
    op.create_index(op.f('ix_ad_accounts_business_manager_id'), 'ad_accounts', ['business_manager_id'], unique=False)
    op.create_index(op.f('ix_ad_accounts_personal_account_reference_id'), 'ad_accounts', ['personal_account_reference_id'], unique=False)
    op.create_index(op.f('ix_ad_accounts_workspace_id'), 'ad_accounts', ['workspace_id'], unique=False)
    op.create_index('ix_ad_accounts_workspace_id_archived_at', 'ad_accounts', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_ad_accounts_workspace_id_last_manual_review_at', 'ad_accounts', ['workspace_id', 'last_manual_review_at'], unique=False)
    op.create_index('ix_ad_accounts_workspace_id_readiness_status', 'ad_accounts', ['workspace_id', 'readiness_status'], unique=False)
    op.create_index('ix_ad_accounts_workspace_id_status', 'ad_accounts', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_ad_accounts_workspace_id_updated_at', 'ad_accounts', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('account_asset_links',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('PAGE', 'PIXEL', 'PAYMENT_PROFILE', 'BROWSER_PROFILE', 'PROXY', name='asset_type', native_enum=False, length=48), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('linked_by', sa.Uuid(), nullable=True),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlinked_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_account_asset_links_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_account_asset_links_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_asset_links'))
    )
    op.create_index(op.f('ix_account_asset_links_ad_account_id'), 'account_asset_links', ['ad_account_id'], unique=False)
    op.create_index('ix_account_asset_links_ad_account_id_asset_type', 'account_asset_links', ['ad_account_id', 'asset_type'], unique=False)
    op.create_index(op.f('ix_account_asset_links_workspace_id'), 'account_asset_links', ['workspace_id'], unique=False)
    op.create_index('ix_account_asset_links_workspace_id_asset_id', 'account_asset_links', ['workspace_id', 'asset_id'], unique=False)
    op.create_table('account_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='event_severity', native_enum=False, length=48), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='event_status', native_enum=False, length=48), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_account_events_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_account_events_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_events'))
    )
    op.create_index(op.f('ix_account_events_ad_account_id'), 'account_events', ['ad_account_id'], unique=False)
    op.create_index('ix_account_events_ad_account_id_status', 'account_events', ['ad_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_account_events_workspace_id'), 'account_events', ['workspace_id'], unique=False)
    op.create_index('ix_account_events_workspace_id_severity', 'account_events', ['workspace_id', 'severity'], unique=False)
    op.create_table('readiness_checklist_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('OWNERSHIP', 'ACCESS', 'BILLING', 'ASSETS', 'COMPLIANCE', 'OPERATIONS', name='checklist_category', native_enum=False, length=48), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('evidence_status', sa.Enum('MISSING', 'PROVIDED', 'VERIFIED', 'EXPIRED', 'REJECTED', name='evidence_status', native_enum=False, length=48), nullable=False),
    sa.Column('review_status', sa.Enum('NOT_REVIEWED', 'IN_REVIEW', 'COMPLETED', 'NEEDS_UPDATE', 'WAIVED', name='checklist_review_status', native_enum=False, length=48), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_readiness_checklist_items_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_readiness_checklist_items_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_checklist_items')),
    sa.UniqueConstraint('ad_account_id', 'item_key', name=op.f('uq_readiness_checklist_items_ad_account_id_item_key'))
    )
    op.create_index(op.f('ix_readiness_checklist_items_ad_account_id'), 'readiness_checklist_items', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_readiness_checklist_items_workspace_id'), 'readiness_checklist_items', ['workspace_id'], unique=False)
    op.create_index('ix_readiness_checklist_items_workspace_id_item_key', 'readiness_checklist_items', ['workspace_id', 'item_key'], unique=False)
    op.create_table('readiness_evidence',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('checklist_item_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('storage_reference', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('provided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provided_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'PROVIDED', 'VERIFIED', 'EXPIRED', 'REJECTED', name='evidence_status', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['readiness_checklist_items.id'], name=op.f('fk_readiness_evidence_checklist_item_id_readiness_checklist_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_readiness_evidence_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_evidence'))
    )
    op.create_index(op.f('ix_readiness_evidence_checklist_item_id'), 'readiness_evidence', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_readiness_evidence_workspace_id'), 'readiness_evidence', ['workspace_id'], unique=False)
    op.create_index('ix_readiness_evidence_workspace_id_archived_at', 'readiness_evidence', ['workspace_id', 'archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_readiness_evidence_workspace_id_archived_at', table_name='readiness_evidence')
    op.drop_index(op.f('ix_readiness_evidence_workspace_id'), table_name='readiness_evidence')
    op.drop_index(op.f('ix_readiness_evidence_checklist_item_id'), table_name='readiness_evidence')
    op.drop_table('readiness_evidence')
    op.drop_index('ix_readiness_checklist_items_workspace_id_item_key', table_name='readiness_checklist_items')
    op.drop_index(op.f('ix_readiness_checklist_items_workspace_id'), table_name='readiness_checklist_items')
    op.drop_index(op.f('ix_readiness_checklist_items_ad_account_id'), table_name='readiness_checklist_items')
    op.drop_table('readiness_checklist_items')
    op.drop_index('ix_account_events_workspace_id_severity', table_name='account_events')
    op.drop_index(op.f('ix_account_events_workspace_id'), table_name='account_events')
    op.drop_index('ix_account_events_ad_account_id_status', table_name='account_events')
    op.drop_index(op.f('ix_account_events_ad_account_id'), table_name='account_events')
    op.drop_table('account_events')
    op.drop_index('ix_account_asset_links_workspace_id_asset_id', table_name='account_asset_links')
    op.drop_index(op.f('ix_account_asset_links_workspace_id'), table_name='account_asset_links')
    op.drop_index('ix_account_asset_links_ad_account_id_asset_type', table_name='account_asset_links')
    op.drop_index(op.f('ix_account_asset_links_ad_account_id'), table_name='account_asset_links')
    op.drop_table('account_asset_links')
    op.drop_index('ix_ad_accounts_workspace_id_updated_at', table_name='ad_accounts')
    op.drop_index('ix_ad_accounts_workspace_id_status', table_name='ad_accounts')
    op.drop_index('ix_ad_accounts_workspace_id_readiness_status', table_name='ad_accounts')
    op.drop_index('ix_ad_accounts_workspace_id_last_manual_review_at', table_name='ad_accounts')
    op.drop_index('ix_ad_accounts_workspace_id_archived_at', table_name='ad_accounts')
    op.drop_index(op.f('ix_ad_accounts_workspace_id'), table_name='ad_accounts')
    op.drop_index(op.f('ix_ad_accounts_personal_account_reference_id'), table_name='ad_accounts')
    op.drop_index(op.f('ix_ad_accounts_business_manager_id'), table_name='ad_accounts')
    op.drop_table('ad_accounts')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_proxy_references_workspace_id_archived_at', table_name='proxy_references')
    op.drop_index(op.f('ix_proxy_references_workspace_id'), table_name='proxy_references')
    op.drop_table('proxy_references')
    op.drop_index('ix_pixels_workspace_id_archived_at', table_name='pixels')
    op.drop_index(op.f('ix_pixels_workspace_id'), table_name='pixels')
    op.drop_table('pixels')
    op.drop_index('ix_personal_account_references_workspace_id_archived_at', table_name='personal_account_references')
    op.drop_index(op.f('ix_personal_account_references_workspace_id'), table_name='personal_account_references')
    op.drop_table('personal_account_references')
    op.drop_index('ix_payment_profile_references_workspace_id_archived_at', table_name='payment_profile_references')
    op.drop_index(op.f('ix_payment_profile_references_workspace_id'), table_name='payment_profile_references')
    op.drop_table('payment_profile_references')
    op.drop_index('ix_pages_workspace_id_archived_at', table_name='pages')
    op.drop_index(op.f('ix_pages_workspace_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_business_managers_workspace_id_archived_at', table_name='business_managers')
    op.drop_index(op.f('ix_business_managers_workspace_id'), table_name='business_managers')
    op.drop_table('business_managers')
    op.drop_index('ix_browser_profile_references_workspace_id_archived_at', table_name='browser_profile_references')
    op.drop_index(op.f('ix_browser_profile_references_workspace_id'), table_name='browser_profile_references')
    op.drop_table('browser_profile_references')
    op.drop_index('ix_audit_logs_workspace_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
