"""A2 account health

Revision ID: 10e675ccb8d8
Revises: 0001_a1_registry
Create Date: 2026-09-04 21:44:02.844386
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_a2_account_health'
down_revision = '0001_a1_registry'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_rule_definitions',
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('rule_key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNT_STATUS', 'OPERATIONS', 'READINESS', 'DATA_QUALITY', name='health_category', native_enum=False, length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('UNKNOWN', 'ATTENTION', 'WARNING', 'CRITICAL', name='signal_severity', native_enum=False, length=48), nullable=False),
    sa.Column('source_requirements_json', sa.JSON(), nullable=False),
    sa.Column('condition_config_json', sa.JSON(), nullable=False),
    sa.Column('freshness_policy_json', sa.JSON(), nullable=True),
    sa.Column('resolution_guidance', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_health_rule_definitions_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_rule_definitions')),
    sa.UniqueConstraint('workspace_id', 'rule_key', 'version', name=op.f('uq_health_rule_definitions_workspace_id_rule_key_version'))
    )
    op.create_index(op.f('ix_health_rule_definitions_workspace_id'), 'health_rule_definitions', ['workspace_id'], unique=False)
    op.create_index('ix_hrd_rule_key_enabled', 'health_rule_definitions', ['rule_key', 'enabled'], unique=False)
    op.create_table('account_health_signals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('rule_definition_id', sa.Uuid(), nullable=True),
    sa.Column('rule_key', sa.String(length=120), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('signal_key', sa.String(length=300), nullable=False),
    sa.Column('active_key', sa.String(length=300), nullable=True),
    sa.Column('category', sa.Enum('ACCOUNT_STATUS', 'OPERATIONS', 'READINESS', 'DATA_QUALITY', name='health_category', native_enum=False, length=48), nullable=False),
    sa.Column('severity', sa.Enum('UNKNOWN', 'ATTENTION', 'WARNING', 'CRITICAL', name='signal_severity', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'EXPIRED', 'SUPERSEDED', name='signal_status', native_enum=False, length=48), nullable=False),
    sa.Column('source_type', sa.Enum('ACCOUNT_STATUS', 'MANUAL_EVENT', 'READINESS_ENGINE', 'CHECKLIST_ITEM', 'EVALUATION_ENGINE', name='health_source_type', native_enum=False, length=48), nullable=False),
    sa.Column('source_entity_type', sa.String(length=80), nullable=True),
    sa.Column('source_entity_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolution_evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_signal_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_account_health_signals_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_definition_id'], ['health_rule_definitions.id'], name='fk_ahs_rule_definition_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_account_health_signals_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_health_signals')),
    sa.UniqueConstraint('ad_account_id', 'active_key', name=op.f('uq_account_health_signals_ad_account_id_active_key'))
    )
    op.create_index(op.f('ix_account_health_signals_ad_account_id'), 'account_health_signals', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_account_health_signals_workspace_id'), 'account_health_signals', ['workspace_id'], unique=False)
    op.create_index('ix_ahs_account_observed_at', 'account_health_signals', ['ad_account_id', 'observed_at'], unique=False)
    op.create_index('ix_ahs_ws_account_status_severity', 'account_health_signals', ['workspace_id', 'ad_account_id', 'status', 'severity'], unique=False)
    op.create_index('ix_ahs_ws_rule_key_status', 'account_health_signals', ['workspace_id', 'rule_key', 'status'], unique=False)
    op.create_table('account_health_snapshots',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('health_status', sa.Enum('UNKNOWN', 'ATTENTION_NEEDED', 'WARNING', 'CRITICAL', 'CLEAR_SIGNALS', name='health_status', native_enum=False, length=48), nullable=False),
    sa.Column('health_summary_json', sa.JSON(), nullable=False),
    sa.Column('open_critical_count', sa.Integer(), nullable=False),
    sa.Column('open_warning_count', sa.Integer(), nullable=False),
    sa.Column('open_attention_count', sa.Integer(), nullable=False),
    sa.Column('open_unknown_count', sa.Integer(), nullable=False),
    sa.Column('freshness_status', sa.Enum('CURRENT', 'STALE', 'UNKNOWN', 'NOT_APPLICABLE', name='health_freshness', native_enum=False, length=48), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_evaluation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_account_health_snapshots_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_account_health_snapshots_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_health_snapshots')),
    sa.UniqueConstraint('ad_account_id', name=op.f('uq_account_health_snapshots_ad_account_id'))
    )
    op.create_index(op.f('ix_account_health_snapshots_ad_account_id'), 'account_health_snapshots', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_account_health_snapshots_workspace_id'), 'account_health_snapshots', ['workspace_id'], unique=False)
    op.create_index('ix_ahsnap_ws_last_evaluated_at', 'account_health_snapshots', ['workspace_id', 'last_evaluated_at'], unique=False)
    op.create_index('ix_ahsnap_ws_status_freshness', 'account_health_snapshots', ['workspace_id', 'health_status', 'freshness_status'], unique=False)
    op.create_table('health_evaluation_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('ad_account_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.Enum('ACCOUNT_MUTATION', 'CHECKLIST_MUTATION', 'EVIDENCE_MUTATION', 'ACCOUNT_EVENT_MUTATION', 'MANUAL_RECALCULATE', 'SCHEDULED_RECALCULATE', 'RULE_CHANGE', 'BACKFILL', name='evaluation_trigger', native_enum=False, length=48), nullable=False),
    sa.Column('trigger_reference_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='evaluation_run_status', native_enum=False, length=48), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_health_evaluation_runs_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_health_evaluation_runs_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_evaluation_runs'))
    )
    op.create_index(op.f('ix_health_evaluation_runs_ad_account_id'), 'health_evaluation_runs', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_health_evaluation_runs_workspace_id'), 'health_evaluation_runs', ['workspace_id'], unique=False)
    op.create_index('ix_her_ws_account_status_created', 'health_evaluation_runs', ['workspace_id', 'ad_account_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_her_ws_account_status_created', table_name='health_evaluation_runs')
    op.drop_index(op.f('ix_health_evaluation_runs_workspace_id'), table_name='health_evaluation_runs')
    op.drop_index(op.f('ix_health_evaluation_runs_ad_account_id'), table_name='health_evaluation_runs')
    op.drop_table('health_evaluation_runs')
    op.drop_index('ix_ahsnap_ws_status_freshness', table_name='account_health_snapshots')
    op.drop_index('ix_ahsnap_ws_last_evaluated_at', table_name='account_health_snapshots')
    op.drop_index(op.f('ix_account_health_snapshots_workspace_id'), table_name='account_health_snapshots')
    op.drop_index(op.f('ix_account_health_snapshots_ad_account_id'), table_name='account_health_snapshots')
    op.drop_table('account_health_snapshots')
    op.drop_index('ix_ahs_ws_rule_key_status', table_name='account_health_signals')
    op.drop_index('ix_ahs_ws_account_status_severity', table_name='account_health_signals')
    op.drop_index('ix_ahs_account_observed_at', table_name='account_health_signals')
    op.drop_index(op.f('ix_account_health_signals_workspace_id'), table_name='account_health_signals')
    op.drop_index(op.f('ix_account_health_signals_ad_account_id'), table_name='account_health_signals')
    op.drop_table('account_health_signals')
    op.drop_index('ix_hrd_rule_key_enabled', table_name='health_rule_definitions')
    op.drop_index(op.f('ix_health_rule_definitions_workspace_id'), table_name='health_rule_definitions')
    op.drop_table('health_rule_definitions')
    # ### end Alembic commands ###
