"""A3 alerts and notifications

Revision ID: d2d838207589
Revises: 0002_a2_account_health
Create Date: 2026-09-04 23:06:57.085526
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0003_a3_alerts'
down_revision = '0002_a2_account_health'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_policies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('critical_bypasses_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('warning_telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('attention_telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_interval_hours', sa.Integer(), nullable=True),
    sa.Column('max_reminders_per_alert', sa.Integer(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_alert_policies_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_policies')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_alert_policies_workspace_id'))
    )
    op.create_index(op.f('ix_alert_policies_workspace_id'), 'alert_policies', ['workspace_id'], unique=False)
    op.create_table('alerts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('HEALTH_SIGNAL', 'HEALTH_EVALUATION_RUN', name='alert_source_type', native_enum=False, length=48), nullable=False),
    sa.Column('source_entity_type', sa.String(length=80), nullable=False),
    sa.Column('source_entity_id', sa.String(length=64), nullable=True),
    sa.Column('alert_key', sa.String(length=400), nullable=False),
    sa.Column('active_key', sa.String(length=400), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'SUPPRESSED', 'RESOLVED', 'EXPIRED', 'ARCHIVED', name='alert_status', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('suppressed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed_by', sa.Uuid(), nullable=True),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('suppression_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_before_suppression', sa.Enum('OPEN', 'ACKNOWLEDGED', 'SUPPRESSED', 'RESOLVED', 'EXPIRED', 'ARCHIVED', name='alert_status', native_enum=False, length=48), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_alerts_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_alerts_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('workspace_id', 'active_key', name=op.f('uq_alerts_workspace_id_active_key'))
    )
    op.create_index(op.f('ix_alerts_ad_account_id'), 'alerts', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_alerts_workspace_id'), 'alerts', ['workspace_id'], unique=False)
    op.create_index('ix_alerts_ws_account_status', 'alerts', ['workspace_id', 'ad_account_id', 'status'], unique=False)
    op.create_index('ix_alerts_ws_alert_key', 'alerts', ['workspace_id', 'alert_key'], unique=False)
    op.create_index('ix_alerts_ws_source', 'alerts', ['workspace_id', 'source_type', 'source_entity_id'], unique=False)
    op.create_index('ix_alerts_ws_status_severity_observed', 'alerts', ['workspace_id', 'status', 'severity', 'last_observed_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', name='delivery_channel', native_enum=False, length=48), nullable=False),
    sa.Column('recipient_reference', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Enum('INITIAL', 'ESCALATION', 'REMINDER', name='delivery_reason', native_enum=False, length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=400), nullable=False),
    sa.Column('message_template_version', sa.String(length=32), nullable=False),
    sa.Column('payload_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENDING', 'SENT', 'FAILED_TRANSIENT', 'FAILED_FINAL', 'SKIPPED', 'CANCELLED', name='delivery_status', native_enum=False, length=48), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quiet_hours_decision', sa.JSON(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sending_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skip_reason', sa.Enum('NO_RECIPIENT_CONFIGURED', 'POLICY_DISABLED', 'SEVERITY_DELIVERY_DISABLED', 'ALERT_SUPPRESSED', 'ALERT_NOT_ACTIVE', 'TIMEZONE_NOT_CONFIGURED', 'DUPLICATE_SUPPRESSED_BY_DEDUPE', 'REMINDERS_DISABLED', name='delivery_skip_reason', native_enum=False, length=48), nullable=True),
    sa.Column('failure_code', sa.Enum('TRANSPORT_NOT_CONFIGURED', 'NETWORK_ERROR', 'RATE_LIMITED', 'PROVIDER_SERVER_ERROR', 'INVALID_RECIPIENT', 'UNAUTHORIZED', 'MESSAGE_REJECTED', 'UNKNOWN_ERROR', name='delivery_failure_code', native_enum=False, length=48), nullable=True),
    sa.Column('failure_summary', sa.String(length=500), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notification_deliveries_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_notification_deliveries_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name=op.f('uq_notification_deliveries_workspace_id_idempotency_key'))
    )
    op.create_index('ix_nd_alert_created', 'notification_deliveries', ['alert_id', 'created_at'], unique=False)
    op.create_index('ix_nd_ws_status_scheduled', 'notification_deliveries', ['workspace_id', 'status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_alert_id'), 'notification_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_workspace_id'), 'notification_deliveries', ['workspace_id'], unique=False)
    op.create_table('notification_delivery_attempts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('notification_delivery_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENDING', 'SENT', 'FAILED_TRANSIENT', 'FAILED_FINAL', 'SKIPPED', 'CANCELLED', name='delivery_status', native_enum=False, length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_response_code', sa.Integer(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.Enum('TRANSPORT_NOT_CONFIGURED', 'NETWORK_ERROR', 'RATE_LIMITED', 'PROVIDER_SERVER_ERROR', 'INVALID_RECIPIENT', 'UNAUTHORIZED', 'MESSAGE_REJECTED', 'UNKNOWN_ERROR', name='delivery_failure_code', native_enum=False, length=48), nullable=True),
    sa.Column('failure_summary', sa.String(length=500), nullable=True),
    sa.Column('retry_scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notification_delivery_id'], ['notification_deliveries.id'], name=op.f('fk_notification_delivery_attempts_notification_delivery_id_notification_deliveries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_notification_delivery_attempts_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery_attempts')),
    sa.UniqueConstraint('notification_delivery_id', 'attempt_number', name=op.f('uq_notification_delivery_attempts_notification_delivery_id_attempt_number'))
    )
    op.create_index('ix_nda_ws_created', 'notification_delivery_attempts', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_delivery_attempts_notification_delivery_id'), 'notification_delivery_attempts', ['notification_delivery_id'], unique=False)
    op.create_index(op.f('ix_notification_delivery_attempts_workspace_id'), 'notification_delivery_attempts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_delivery_attempts_workspace_id'), table_name='notification_delivery_attempts')
    op.drop_index(op.f('ix_notification_delivery_attempts_notification_delivery_id'), table_name='notification_delivery_attempts')
    op.drop_index('ix_nda_ws_created', table_name='notification_delivery_attempts')
    op.drop_table('notification_delivery_attempts')
    op.drop_index(op.f('ix_notification_deliveries_workspace_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_alert_id'), table_name='notification_deliveries')
    op.drop_index('ix_nd_ws_status_scheduled', table_name='notification_deliveries')
    op.drop_index('ix_nd_alert_created', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_alerts_ws_status_severity_observed', table_name='alerts')
    op.drop_index('ix_alerts_ws_source', table_name='alerts')
    op.drop_index('ix_alerts_ws_alert_key', table_name='alerts')
    op.drop_index('ix_alerts_ws_account_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_workspace_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ad_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_policies_workspace_id'), table_name='alert_policies')
    op.drop_table('alert_policies')
    # ### end Alembic commands ###
