"""A6: Preflight Compliance Gate — campaign drafts, findings, evaluation runs, landing-page
evidence.

Four additive tables. No A1-A5 table is altered: A6 reads A1 readiness and A2 health through
their existing services, never through a duplicate SQL path against those tables.

Revision ID: 0006_a6_preflight
Revises: 0005_a5_extension
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0006_a6_preflight"
down_revision = "0005_a5_extension"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_drafts",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("ad_account_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.String(length=80), nullable=True),
        sa.Column("primary_copy", sa.Text(), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("call_to_action", sa.String(length=80), nullable=True),
        sa.Column("landing_page_url", sa.String(length=2000), nullable=True),
        sa.Column("creative_reference", sa.String(length=2000), nullable=True),
        sa.Column("budget_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("budget_currency", sa.String(length=8), nullable=True),
        sa.Column("budget_change_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("targeting_summary", sa.Text(), nullable=True),
        sa.Column(
            "draft_status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED_FOR_REVIEW",
                "NEEDS_CHANGES",
                "READY_FOR_MANUAL_REVIEW",
                "BLOCKED_BY_INTERNAL_POLICY",
                "UNKNOWN_MISSING_EVIDENCE",
                "ARCHIVED",
                name="draft_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_campaign_drafts_ad_account_id_ad_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaign_drafts_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_drafts")),
    )
    op.create_index(
        op.f("ix_campaign_drafts_ad_account_id"), "campaign_drafts", ["ad_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_drafts_workspace_id"), "campaign_drafts", ["workspace_id"], unique=False
    )
    op.create_index("ix_cd_ws_account", "campaign_drafts", ["workspace_id", "ad_account_id"], unique=False)
    op.create_index(
        "ix_cd_ws_status_updated",
        "campaign_drafts",
        ["workspace_id", "draft_status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "preflight_evaluation_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="preflight_evaluation_run_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("result_summary_json", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["campaign_drafts.id"],
            name=op.f("fk_preflight_evaluation_runs_draft_id_campaign_drafts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_preflight_evaluation_runs_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preflight_evaluation_runs")),
    )
    op.create_index(
        "ix_per_ws_draft_status_created",
        "preflight_evaluation_runs",
        ["workspace_id", "draft_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preflight_evaluation_runs_draft_id"), "preflight_evaluation_runs", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_preflight_evaluation_runs_workspace_id"),
        "preflight_evaluation_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "landing_page_evidence",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("final_url", sa.String(length=2000), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("is_https", sa.Boolean(), nullable=False),
        sa.Column("redirect_count", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("mobile_viewport_meta_present", sa.Boolean(), nullable=True),
        sa.Column("contact_or_policy_link_detected", sa.Boolean(), nullable=True),
        sa.Column("fetch_error", sa.String(length=200), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["campaign_drafts.id"],
            name=op.f("fk_landing_page_evidence_draft_id_campaign_drafts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["preflight_evaluation_runs.id"],
            name=op.f("fk_landing_page_evidence_evaluation_run_id_preflight_evaluation_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_landing_page_evidence_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_landing_page_evidence")),
    )
    op.create_index(
        op.f("ix_landing_page_evidence_draft_id"), "landing_page_evidence", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_landing_page_evidence_workspace_id"), "landing_page_evidence", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_lpe_ws_draft_checked",
        "landing_page_evidence",
        ["workspace_id", "draft_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "preflight_findings",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "COPY_LANGUAGE",
                "LANDING_PAGE",
                "ACCOUNT_READINESS",
                "ACCOUNT_HEALTH",
                "BUDGET_CHANGE",
                "TARGETING_COMPLETENESS",
                "DATA_QUALITY",
                name="finding_category",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("INFO", "WARNING", "BLOCKING", name="finding_severity", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("rule_key", sa.String(length=120), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("field_reference", sa.String(length=120), nullable=True),
        sa.Column("evidence_reference", sa.String(length=120), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ACKNOWLEDGED",
                "RESOLVED",
                "SUPERSEDED",
                name="finding_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["campaign_drafts.id"],
            name=op.f("fk_preflight_findings_draft_id_campaign_drafts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["preflight_evaluation_runs.id"],
            name=op.f("fk_preflight_findings_evaluation_run_id_preflight_evaluation_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_preflight_findings_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preflight_findings")),
    )
    op.create_index("ix_pf_evaluation_run", "preflight_findings", ["evaluation_run_id"], unique=False)
    op.create_index(
        "ix_pf_ws_draft_status_severity",
        "preflight_findings",
        ["workspace_id", "draft_id", "status", "severity"],
        unique=False,
    )
    op.create_index(op.f("ix_preflight_findings_draft_id"), "preflight_findings", ["draft_id"], unique=False)
    op.create_index(
        op.f("ix_preflight_findings_workspace_id"), "preflight_findings", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preflight_findings_workspace_id"), table_name="preflight_findings")
    op.drop_index(op.f("ix_preflight_findings_draft_id"), table_name="preflight_findings")
    op.drop_index("ix_pf_ws_draft_status_severity", table_name="preflight_findings")
    op.drop_index("ix_pf_evaluation_run", table_name="preflight_findings")
    op.drop_table("preflight_findings")
    op.drop_index("ix_lpe_ws_draft_checked", table_name="landing_page_evidence")
    op.drop_index(op.f("ix_landing_page_evidence_workspace_id"), table_name="landing_page_evidence")
    op.drop_index(op.f("ix_landing_page_evidence_draft_id"), table_name="landing_page_evidence")
    op.drop_table("landing_page_evidence")
    op.drop_index(op.f("ix_preflight_evaluation_runs_workspace_id"), table_name="preflight_evaluation_runs")
    op.drop_index(op.f("ix_preflight_evaluation_runs_draft_id"), table_name="preflight_evaluation_runs")
    op.drop_index("ix_per_ws_draft_status_created", table_name="preflight_evaluation_runs")
    op.drop_table("preflight_evaluation_runs")
    op.drop_index("ix_cd_ws_status_updated", table_name="campaign_drafts")
    op.drop_index("ix_cd_ws_account", table_name="campaign_drafts")
    op.drop_index(op.f("ix_campaign_drafts_workspace_id"), table_name="campaign_drafts")
    op.drop_index(op.f("ix_campaign_drafts_ad_account_id"), table_name="campaign_drafts")
    op.drop_table("campaign_drafts")
    # ### end Alembic commands ###
