"""A7: BM + ad account creation & sharing via the official Meta API only.

Five additive tables. No A1 table is altered — a successfully created account syncs into
`ad_accounts` through the existing registry service, not a duplicate write path here. No token
is ever a column in any table here.

Revision ID: 0007_a7_meta_ops
Revises: 0006_a6_preflight
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0007_a7_meta_ops"
down_revision = "0006_a6_preflight"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meta_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("FAKE", "SANDBOX", "PRODUCTION", name="meta_environment", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UNKNOWN",
                "ACTIVE",
                "INACTIVE",
                "RESTRICTED",
                name="reference_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("capabilities_json", sa.JSON(), nullable=True),
        sa.Column("last_capability_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("business_managers_json", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_connections_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_connections")),
    )
    op.create_index("ix_meta_conn_ws_status", "meta_connections", ["workspace_id", "status"], unique=False)
    op.create_index(
        op.f("ix_meta_connections_workspace_id"), "meta_connections", ["workspace_id"], unique=False
    )
    op.create_table(
        "meta_access_share_batches",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("meta_connection_id", sa.Uuid(), nullable=False),
        sa.Column("preview_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meta_connection_id"],
            ["meta_connections.id"],
            name=op.f("fk_meta_access_share_batches_meta_connection_id_meta_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_access_share_batches_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_access_share_batches")),
    )
    op.create_index(
        "ix_masb_ws_confirmed", "meta_access_share_batches", ["workspace_id", "confirmed_at"], unique=False
    )
    op.create_index(
        op.f("ix_meta_access_share_batches_workspace_id"),
        "meta_access_share_batches",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "meta_account_creation_batches",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("meta_connection_id", sa.Uuid(), nullable=False),
        sa.Column("business_manager_external_id", sa.String(length=120), nullable=False),
        sa.Column("preview_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meta_connection_id"],
            ["meta_connections.id"],
            name=op.f("fk_meta_account_creation_batches_meta_connection_id_meta_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_account_creation_batches_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_account_creation_batches")),
    )
    op.create_index(
        "ix_macb_ws_confirmed",
        "meta_account_creation_batches",
        ["workspace_id", "confirmed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_account_creation_batches_workspace_id"),
        "meta_account_creation_batches",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "meta_access_share_batch_items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_ad_account_id", sa.Uuid(), nullable=True),
        sa.Column("source_external_account_id", sa.String(length=120), nullable=False),
        sa.Column("recipient_reference", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "UNKNOWN",
                name="meta_batch_item_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("access_grant_reference", sa.String(length=200), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["meta_access_share_batches.id"],
            name=op.f("fk_meta_access_share_batch_items_batch_id_meta_access_share_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_meta_access_share_batch_items_source_ad_account_id_ad_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_access_share_batch_items_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_access_share_batch_items")),
        sa.UniqueConstraint(
            "workspace_id",
            "idempotency_key",
            name=op.f("uq_meta_access_share_batch_items_workspace_id_idempotency_key"),
        ),
    )
    op.create_index(
        "ix_masbi_batch_status", "meta_access_share_batch_items", ["batch_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_meta_access_share_batch_items_batch_id"),
        "meta_access_share_batch_items",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_access_share_batch_items_workspace_id"),
        "meta_access_share_batch_items",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "meta_account_creation_batch_items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "UNKNOWN",
                name="meta_batch_item_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("external_account_id", sa.String(length=120), nullable=True),
        sa.Column("synced_ad_account_id", sa.Uuid(), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["meta_account_creation_batches.id"],
            name=op.f("fk_meta_account_creation_batch_items_batch_id_meta_account_creation_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synced_ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_meta_account_creation_batch_items_synced_ad_account_id_ad_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_account_creation_batch_items_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_account_creation_batch_items")),
        sa.UniqueConstraint(
            "workspace_id",
            "idempotency_key",
            name=op.f("uq_meta_account_creation_batch_items_workspace_id_idempotency_key"),
        ),
    )
    op.create_index(
        "ix_macbi_batch_status", "meta_account_creation_batch_items", ["batch_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_meta_account_creation_batch_items_batch_id"),
        "meta_account_creation_batch_items",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_account_creation_batch_items_workspace_id"),
        "meta_account_creation_batch_items",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meta_account_creation_batch_items_workspace_id"),
        table_name="meta_account_creation_batch_items",
    )
    op.drop_index(
        op.f("ix_meta_account_creation_batch_items_batch_id"), table_name="meta_account_creation_batch_items"
    )
    op.drop_index("ix_macbi_batch_status", table_name="meta_account_creation_batch_items")
    op.drop_table("meta_account_creation_batch_items")
    op.drop_index(
        op.f("ix_meta_access_share_batch_items_workspace_id"), table_name="meta_access_share_batch_items"
    )
    op.drop_index(
        op.f("ix_meta_access_share_batch_items_batch_id"), table_name="meta_access_share_batch_items"
    )
    op.drop_index("ix_masbi_batch_status", table_name="meta_access_share_batch_items")
    op.drop_table("meta_access_share_batch_items")
    op.drop_index(
        op.f("ix_meta_account_creation_batches_workspace_id"), table_name="meta_account_creation_batches"
    )
    op.drop_index("ix_macb_ws_confirmed", table_name="meta_account_creation_batches")
    op.drop_table("meta_account_creation_batches")
    op.drop_index(op.f("ix_meta_access_share_batches_workspace_id"), table_name="meta_access_share_batches")
    op.drop_index("ix_masb_ws_confirmed", table_name="meta_access_share_batches")
    op.drop_table("meta_access_share_batches")
    op.drop_index(op.f("ix_meta_connections_workspace_id"), table_name="meta_connections")
    op.drop_index("ix_meta_conn_ws_status", table_name="meta_connections")
    op.drop_table("meta_connections")
    # ### end Alembic commands ###
