"""A8: Bulk Pixel Share via the official Meta API — reuses A7's batch engine exactly (same
preview_hash/confirm/idempotency/retry shape), adding exactly one operation type.

Revision ID: 0008_a8_pixel_share
Revises: 0007_a7_meta_ops
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0008_a8_pixel_share"
down_revision = "0007_a7_meta_ops"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meta_pixel_share_batches",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("meta_connection_id", sa.Uuid(), nullable=False),
        sa.Column("preview_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meta_connection_id"],
            ["meta_connections.id"],
            name=op.f("fk_meta_pixel_share_batches_meta_connection_id_meta_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_pixel_share_batches_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_pixel_share_batches")),
    )
    op.create_index(
        op.f("ix_meta_pixel_share_batches_workspace_id"),
        "meta_pixel_share_batches",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_mpsb_ws_confirmed", "meta_pixel_share_batches", ["workspace_id", "confirmed_at"], unique=False
    )
    op.create_table(
        "meta_pixel_share_batch_items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_pixel_id", sa.Uuid(), nullable=True),
        sa.Column("source_external_pixel_id", sa.String(length=120), nullable=False),
        sa.Column("target_ad_account_id", sa.Uuid(), nullable=True),
        sa.Column("target_ad_account_external_id", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "UNKNOWN",
                name="meta_batch_item_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("access_grant_reference", sa.String(length=200), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["meta_pixel_share_batches.id"],
            name=op.f("fk_meta_pixel_share_batch_items_batch_id_meta_pixel_share_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_pixel_id"],
            ["pixels.id"],
            name=op.f("fk_meta_pixel_share_batch_items_source_pixel_id_pixels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_meta_pixel_share_batch_items_target_ad_account_id_ad_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meta_pixel_share_batch_items_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meta_pixel_share_batch_items")),
        sa.UniqueConstraint(
            "workspace_id",
            "idempotency_key",
            name=op.f("uq_meta_pixel_share_batch_items_workspace_id_idempotency_key"),
        ),
    )
    op.create_index(
        op.f("ix_meta_pixel_share_batch_items_batch_id"),
        "meta_pixel_share_batch_items",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meta_pixel_share_batch_items_workspace_id"),
        "meta_pixel_share_batch_items",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_mpsbi_batch_status", "meta_pixel_share_batch_items", ["batch_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mpsbi_batch_status", table_name="meta_pixel_share_batch_items")
    op.drop_index(
        op.f("ix_meta_pixel_share_batch_items_workspace_id"), table_name="meta_pixel_share_batch_items"
    )
    op.drop_index(op.f("ix_meta_pixel_share_batch_items_batch_id"), table_name="meta_pixel_share_batch_items")
    op.drop_table("meta_pixel_share_batch_items")
    op.drop_index("ix_mpsb_ws_confirmed", table_name="meta_pixel_share_batches")
    op.drop_index(op.f("ix_meta_pixel_share_batches_workspace_id"), table_name="meta_pixel_share_batches")
    op.drop_table("meta_pixel_share_batches")
    # ### end Alembic commands ###
