"""a9 team seats device session

Revision ID: 4f3ba575d1b0
Revises: 0008_a8_pixel_share
Create Date: 2026-09-09 14:03:23.544873
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0009_a9_device_session'
down_revision = '0008_a8_pixel_share'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_sessions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_type', sa.Enum('WEB', name='device_session_type', native_enum=False, length=48), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('browser_family', sa.String(length=60), nullable=True),
    sa.Column('os_family', sa.String(length=60), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_device_sessions_revoked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_device_sessions_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sessions'))
    )
    op.create_index(op.f('ix_device_sessions_user_id'), 'device_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_sessions_workspace_id'), 'device_sessions', ['workspace_id'], unique=False)
    op.create_index('ix_device_sessions_ws_user', 'device_sessions', ['workspace_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_sessions_ws_user', table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_workspace_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_user_id'), table_name='device_sessions')
    op.drop_table('device_sessions')
    # ### end Alembic commands ###
