"""a9 seat plan invitation assignment

Revision ID: f7a83c9cd51d
Revises: 0009_a9_device_session
Create Date: 2026-09-09 14:51:24.198136
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0010_a9_seat_invite_assign'
down_revision = '0009_a9_device_session'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('invited_role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', 'CANCELLED', 'ARCHIVED', name='invitation_status', native_enum=False, length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_last_four', sa.String(length=4), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_workspace_invitations_accepted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspace_invitations_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_workspace_invitations_revoked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invitations_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_workspace_invitations_token_hash'))
    )
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_invitations_ws_email', 'workspace_invitations', ['workspace_id', 'email_normalized'], unique=False)
    op.create_table('workspace_seat_plans',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('plan_reference', sa.String(length=120), nullable=True),
    sa.Column('plan_status', sa.Enum('ACTIVE', name='seat_plan_status', native_enum=False, length=48), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspace_seat_plans_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_workspace_seat_plans_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_seat_plans_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_seat_plans')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_workspace_seat_plans_workspace_id'))
    )
    op.create_index(op.f('ix_workspace_seat_plans_workspace_id'), 'workspace_seat_plans', ['workspace_id'], unique=False)
    op.create_table('member_business_manager_assignments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('business_manager_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='assignment_status', native_enum=False, length=48), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_member_business_manager_assignments_assigned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_manager_id'], ['business_managers.id'], name=op.f('fk_member_business_manager_assignments_business_manager_id_business_managers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], name=op.f('fk_member_business_manager_assignments_member_id_workspace_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_member_business_manager_assignments_revoked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_member_business_manager_assignments_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_business_manager_assignments'))
    )
    op.create_index('ix_member_bm_assignments_bm', 'member_business_manager_assignments', ['business_manager_id'], unique=False)
    op.create_index('ix_member_bm_assignments_ws_member', 'member_business_manager_assignments', ['workspace_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_member_business_manager_assignments_workspace_id'), 'member_business_manager_assignments', ['workspace_id'], unique=False)
    op.create_table('member_ad_account_assignments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='assignment_status', native_enum=False, length=48), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], name=op.f('fk_member_ad_account_assignments_ad_account_id_ad_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_member_ad_account_assignments_assigned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], name=op.f('fk_member_ad_account_assignments_member_id_workspace_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_member_ad_account_assignments_revoked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_member_ad_account_assignments_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_ad_account_assignments'))
    )
    op.create_index('ix_member_account_assignments_account', 'member_ad_account_assignments', ['ad_account_id'], unique=False)
    op.create_index('ix_member_account_assignments_ws_member', 'member_ad_account_assignments', ['workspace_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_member_ad_account_assignments_workspace_id'), 'member_ad_account_assignments', ['workspace_id'], unique=False)
    # `server_default` so this is safe on a workspace_members table that already has rows —
    # every existing member becomes `active`, the same status the bootstrap owner is created
    # with (app/bootstrap.py never sets suspended/deactivated). Kept permanently (not dropped
    # after), matching this project's own precedent in 0005_a5_extension.py.
    op.add_column(
        'workspace_members',
        sa.Column(
            'status',
            sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='workspace_member_status', native_enum=False, length=48),
            nullable=False,
            server_default='ACTIVE',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'status')
    op.drop_index(op.f('ix_member_ad_account_assignments_workspace_id'), table_name='member_ad_account_assignments')
    op.drop_index('ix_member_account_assignments_ws_member', table_name='member_ad_account_assignments')
    op.drop_index('ix_member_account_assignments_account', table_name='member_ad_account_assignments')
    op.drop_table('member_ad_account_assignments')
    op.drop_index(op.f('ix_member_business_manager_assignments_workspace_id'), table_name='member_business_manager_assignments')
    op.drop_index('ix_member_bm_assignments_ws_member', table_name='member_business_manager_assignments')
    op.drop_index('ix_member_bm_assignments_bm', table_name='member_business_manager_assignments')
    op.drop_table('member_business_manager_assignments')
    op.drop_index(op.f('ix_workspace_seat_plans_workspace_id'), table_name='workspace_seat_plans')
    op.drop_table('workspace_seat_plans')
    op.drop_index('ix_workspace_invitations_ws_email', table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    # ### end Alembic commands ###
