"""a10_1 discovery

Revision ID: 0011_a10_1_discovery
Revises: 0010_a9_seat_invite_assign
Create Date: 2026-09-10 15:07:38.340738
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0011_a10_1_discovery'
down_revision = '0010_a9_seat_invite_assign'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_manager_discovery_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('meta_connection_id', sa.Uuid(), nullable=False),
    sa.Column('configured_business_manager_reference', sa.String(length=120), nullable=False),
    sa.Column('configured_business_manager_name', sa.String(length=200), nullable=True),
    sa.Column('trigger', sa.Enum('MANUAL', 'INTERNAL_TEST', name='discovery_trigger', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', name='discovery_run_status', native_enum=False, length=48), nullable=False),
    sa.Column('provider_environment', sa.Enum('FAKE', 'SANDBOX', 'PRODUCTION', name='meta_environment', native_enum=False, length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ad_account_required_edges_json', sa.JSON(), nullable=True),
    sa.Column('pixel_required_edges_json', sa.JSON(), nullable=True),
    sa.Column('ad_account_coverage_json', sa.JSON(), nullable=True),
    sa.Column('pixel_coverage_json', sa.JSON(), nullable=True),
    sa.Column('ad_account_coverage_status', sa.Enum('COMPLETE', 'PARTIAL', 'INCOMPLETE', 'UNKNOWN', 'STALE', 'NOT_ATTEMPTED', name='coverage_status', native_enum=False, length=48), nullable=False),
    sa.Column('pixel_coverage_status', sa.Enum('COMPLETE', 'PARTIAL', 'INCOMPLETE', 'UNKNOWN', 'STALE', 'NOT_ATTEMPTED', name='coverage_status', native_enum=False, length=48), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meta_connection_id'], ['meta_connections.id'], name=op.f('fk_business_manager_discovery_runs_meta_connection_id_meta_connections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_business_manager_discovery_runs_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_manager_discovery_runs'))
    )
    op.create_index('ix_bm_discovery_ws_conn_created', 'business_manager_discovery_runs', ['workspace_id', 'meta_connection_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_business_manager_discovery_runs_meta_connection_id'), 'business_manager_discovery_runs', ['meta_connection_id'], unique=False)
    op.create_index(op.f('ix_business_manager_discovery_runs_workspace_id'), 'business_manager_discovery_runs', ['workspace_id'], unique=False)
    op.create_table('discovered_ad_account_observations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('business_manager_discovery_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider_business_manager_id', sa.String(length=120), nullable=False),
    sa.Column('external_account_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('source_edge', sa.String(length=60), nullable=False),
    sa.Column('safe_metadata_json', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_manager_discovery_run_id'], ['business_manager_discovery_runs.id'], name=op.f('fk_discovered_ad_account_observations_business_manager_discovery_run_id_business_manager_discovery_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_discovered_ad_account_observations_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_ad_account_observations'))
    )
    op.create_index('ix_disc_acct_ws_run_ext', 'discovered_ad_account_observations', ['workspace_id', 'business_manager_discovery_run_id', 'external_account_id'], unique=False)
    op.create_index(op.f('ix_discovered_ad_account_observations_business_manager_discovery_run_id'), 'discovered_ad_account_observations', ['business_manager_discovery_run_id'], unique=False)
    op.create_index(op.f('ix_discovered_ad_account_observations_workspace_id'), 'discovered_ad_account_observations', ['workspace_id'], unique=False)
    op.create_table('discovered_pixel_observations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('business_manager_discovery_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider_business_manager_id', sa.String(length=120), nullable=False),
    sa.Column('external_pixel_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('source_edge', sa.String(length=60), nullable=False),
    sa.Column('safe_metadata_json', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_manager_discovery_run_id'], ['business_manager_discovery_runs.id'], name=op.f('fk_discovered_pixel_observations_business_manager_discovery_run_id_business_manager_discovery_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_discovered_pixel_observations_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_pixel_observations'))
    )
    op.create_index('ix_disc_pixel_ws_run_ext', 'discovered_pixel_observations', ['workspace_id', 'business_manager_discovery_run_id', 'external_pixel_id'], unique=False)
    op.create_index(op.f('ix_discovered_pixel_observations_business_manager_discovery_run_id'), 'discovered_pixel_observations', ['business_manager_discovery_run_id'], unique=False)
    op.create_index(op.f('ix_discovered_pixel_observations_workspace_id'), 'discovered_pixel_observations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_pixel_observations_workspace_id'), table_name='discovered_pixel_observations')
    op.drop_index(op.f('ix_discovered_pixel_observations_business_manager_discovery_run_id'), table_name='discovered_pixel_observations')
    op.drop_index('ix_disc_pixel_ws_run_ext', table_name='discovered_pixel_observations')
    op.drop_table('discovered_pixel_observations')
    op.drop_index(op.f('ix_discovered_ad_account_observations_workspace_id'), table_name='discovered_ad_account_observations')
    op.drop_index(op.f('ix_discovered_ad_account_observations_business_manager_discovery_run_id'), table_name='discovered_ad_account_observations')
    op.drop_index('ix_disc_acct_ws_run_ext', table_name='discovered_ad_account_observations')
    op.drop_table('discovered_ad_account_observations')
    op.drop_index(op.f('ix_business_manager_discovery_runs_workspace_id'), table_name='business_manager_discovery_runs')
    op.drop_index(op.f('ix_business_manager_discovery_runs_meta_connection_id'), table_name='business_manager_discovery_runs')
    op.drop_index('ix_bm_discovery_ws_conn_created', table_name='business_manager_discovery_runs')
    op.drop_table('business_manager_discovery_runs')
    # ### end Alembic commands ###
