"""a10_2 timezone id

Revision ID: 0012_a10_2_timezone_id
Revises: 0011_a10_1_discovery
Create Date: 2026-09-11 11:54:36.771576
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0012_a10_2_timezone_id'
down_revision = '0011_a10_1_discovery'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_account_creation_batch_items', sa.Column('timezone_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_account_creation_batch_items', 'timezone_id')
    # ### end Alembic commands ###
