"""a10_2 discovery actor

Revision ID: 0013_a10_2_actor
Revises: 0012_a10_2_timezone_id
Create Date: 2026-09-11 14:49:19.052116
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0013_a10_2_actor'
down_revision = '0012_a10_2_timezone_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_manager_discovery_runs', sa.Column('provider_actor_external_id', sa.String(length=120), nullable=True))
    op.add_column('business_manager_discovery_runs', sa.Column('provider_actor_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_manager_discovery_runs', 'provider_actor_name')
    op.drop_column('business_manager_discovery_runs', 'provider_actor_external_id')
    # ### end Alembic commands ###
